name: reviewdog
on: [pull_request]
jobs:
  node-checks:
    name: Node checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: yarn install
      - uses: reviewdog/action-eslint@v1
        with:
          reporter: github-pr-review
          level: warning
          fail_on_error: true
      - uses: reviewdog/action-stylelint@v1
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          level: warning
          fail_on_error: true
      - name: tsc
        run: yarn workspaces run check
  golang-checks:
    name: Golang checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set golang version
        run: |
          echo "GO_VERSION=$(grep 'go ' go.mod -m 1 | awk '{print $2}')" >> $GITHUB_ENV
      - uses: reviewdog/action-golangci-lint@v2
        with:
          reporter: github-pr-review
          level: warning
          fail_on_error: true
          go_version: ${{ env.GO_VERSION }}
